name: Deploy docs to GitHub pages
on:
  push:
    # this is the branch where you develop your site
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:     

    - name: checkout
      uses: actions/checkout@v2
    
    - name: Generate static docs files
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.4'

    - name: Install
      run: |
        npm ci
        npx typedoc src/* --out docs/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
         folder: docs
         branch: gh-pages
